services:
  habesha-com:
    container_name: habesha-com
    build:
      context: .
    restart: unless-stopped
   # ports:
    #  - "8080"
    environment:
      - HOST=0.0.0.0
      - VIRTUAL_HOST=www.habesha.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=www.habesha.com 
      - LETSENCRYPT_EMAIL=admin@habesha.com
      - VITE_API_URL=/api
    networks:
      - nginx_proxy
    volumes:
      - ./:/app       # Mount your code from host
      - /app/node_modules   # Prevent overwriting container's node_modules
   
    

networks:
  nginx_proxy:
    external: true 
 

