version: '3.8'

services:
  habesha-com:
    container_name: habesha-com
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=www.habesha.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=www.habesha.com
      - LETSENCRYPT_EMAIL=admin@habesha.com
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true 
 

